version: '3.4'

services:
  codehero.lowerorhigheryoutube.api:
    image: ${DOCKER_REGISTRY-}codeherolowerorhigheryoutubeapi
    build:
      context: .
      dockerfile: CodeHero.LowerOrHigherYouTube.API/Dockerfile
    ports:
    - "5000:80"

  postgres:
    image: postgres:14.0
    restart: always
    environment:
      - POSTGRES_DB=code-hero
      - POSTGRES_USER=code-hero-admin
      - POSTGRES_PASSWORD=admin123456
    ports:
    - "5432:5432"

  pgadmin:
    depends_on:
    - postgres
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=code-hero-admin@lowerorhigheryoutube.com
      - PGADMIN_DEFAULT_PASSWORD=admin123456
    restart: always
    ports:
    - "5003:80"