version: '3.4'

services:
  codehero.lowerorhigheryoutube.api:
    depends_on:
    - postgres
    image: ${DOCKER_REGISTRY-}lowerorhigheryoutubeapi
    build:
      context: .
      dockerfile: CodeHero.LowerOrHigherYouTube.API/Dockerfile
    ports:
    - "5011:80"
  
  postgres:
    image: postgres:13.2
    restart: always
    environment:
      - POSTGRES_DB=HigherOrLowerYouTube
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
    expose:
    - "5432"

  codehero.lowerorhigheryoutube.frontend:
    depends_on:
    - codehero.lowerorhigheryoutube.api
    image: ${DOCKER_REGISTRY-}lowerorhigheryoutubefrontend:v1
    restart: always
    ports:
    - "5010:80"